### ISSUE TITLE
Tab 组件的标签可点击区域问题

### ISSUE THREAD

**Issue by zpbx** [baixing/Puerh#10]
请先看下图：

![tab](https://f.cloud.github.com/assets/5830104/1470881/d3c235ca-45cb-11e3-8714-e5077404626c.jpg)

### 问题描述

这个组件的结构是： `ul.tab-title > (li.tab-title-item > a) * n`

从设计上看（或者一般来说），整个 tab 标签页都应该是可响应点击操作的。不过由于 a 是行内元素，即使我们已经将其行高设置为 32px（刚好充满 li 的高度），它的可点击区域也只能覆盖到文字区域（即图中的阴影部分是不可响应点击的）。

### 解决方案

让 a 成为块级元素即可。同时为了防止在 IE7- 下 a 在水平方向上撑开 li，可以给 a 加左浮动，令其收缩宽度。保险起见，还可以再给 a 加 `{white-space: nowrap}` 。

另外 li 的高度其实可以去掉，因为 a 已经有明确高度了。

***

#### 注意

由于目前暂不确定是本项目库和 haojing 所用的 Puerh 的版本是否一致，目前先在 haojing 修复此问题。此 issue 在本项目库仅做存档，待有必要时将修改应用到本项目库。

**Comment by amio** [comment]
搞定，关掉
