### ISSUE TITLE
Tips/Pops 控件需要增强

### ISSUE THREAD

**Issue by amio** [baixing/puerh#22]
目前的 tips 不能满足人民群众日益增长的开发需求，需要更多功能。

@ymdqqqq  @HerringtonDarkholme 来确定下需要的功能和 API 吧

**Comment by amio** [comment]
祥子：
赞~大家赶紧提需求~

绵羊：
赞！
需求：希望能有更好看的小尖
比如赶集这种：http://sh.ganji.com/zpshichangyingxiao/

大炜：
样子比我们好些，
不过看了下实现，赶集这个浮层也是够了，
所有内容都写成 display:none 的元素，基本上相当于我们在 jade 里输出所有HTML的做法。

每个 tip 有 34 个元素，页面里总共 77 个 tip， 这一项功能就给页面加了 2618 个 HTMLElement。
全页面的 dom 数是 4883，一多半都是这个 tips 的。
性能杀手，很多 jQuery 的选择器都会被这个拖累。
我们不能这么做。

考虑做成配置项，按元素上的属性配置动态生成 tip 元素，
配置接口大概这样吧（三种调用方式）：
- <a class="puerh-tips" tips-data="context.item" tips-template="underscore-template" tips-pos="top" />
- <a class="puerh-tips" tips-text="Simple Tip" />
- <a class="puerh-tips" tips="context.itemdata" />

鹏哥：
如果需要弹出富文本提示，就不要在 tooltip 组件上改了。Puerh 的 JS 组件基于 Bootstrap，直接放出 popover 组件应该更合适。

绵羊：
popover有bug。
以前写某个case的时候试过了。
@前端架构的同学：
吧popover修好？

大炜：
那更好，
解决方式不一定要重新造轮子，
也许考虑升级 Puerh 依赖的 Bootstrap 2 到新版本会更方便，也带来更多新组件。

绵羊：
支持更新puerh！

大炜：
popover 的问题属于 Bootstrap，
解决的话最好去 bootstrap 的 repo 上搞定（很可能他们的升级早已 fix 了）
所以我们最好升级下 Bootstrap 吧，能解决一大堆需求，文档也现成的了。

甘弟：
popover应该是缺少对应的CSS
puerh用了bootstrap的js库，但是没有直接引对应的样式

**Comment by amio** [comment]
经过更进一步了解，Puerh 升级 Bootstrap 的方案也不大合适，
还是在 Puerh 上增强这部分控件吧。

后面的计划是先整理 haojing 内的 Puerh，拆分成小组件，然后从升级 tips/pops 组件开始搞。

**Comment by wyhw** [comment]
Bootstrap 太大了吧....

2015-06-01 16:46 GMT+08:00 Amio <notifications@github.com>:

> Closed #22 <https://github.com/baixing/puerh/issues/22>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baixing/puerh/issues/22#event-318550481>.
>



-- 
-- 
Best Regards,

王卫华 Wyhw
百姓网www.baixing.com
世界500强eBay全球成员

FAX:021-52589825
Mob:13917067724
E-mail:wangweihua@baixing.com <wangweihua@baixing.com>
MSN:wyhw2002@hotmail.com

**Comment by amio** [comment]
是该拆分下了
