### ISSUE TITLE
固底广告条

### ISSUE THREAD

**Issue by amio** [baixing/Puerh#23]
【代发Issue，量大从优】

@HerringtonDarkholme @ymdqqqq 鹏哥稍后会找你们聊具体的需求
或者你们主动归纳下贴过来~

**Comment by cssmagic** [comment]
Puerh 的增加和维护这件事情的 owner 待定。艾芙 (@xu-yanfei) 会做统筹安排。

如果是 WAP 的 UI 需求，请两位 [到 CMUI 项目发 issue](https://github.com/CMUI/CMUI/issues)。我会处理，谢谢 :smile:

**Comment by hax** [comment]
这case归属cmui。
