### ISSUE TITLE
已把 Puerh 注册到 Bower

### ISSUE THREAD

**Issue by cssmagic** [baixing/puerh#24]
已把 Puerh 注册到 Bower，合理占坑还是有必要的。

现在可以通过 Bower 安装：

```sh
$ bower i puerh
```

接下来，README 可以做相应说明。

**Comment by amio** [comment]
赞，都没人想起来这个……

**Comment by sofish** [comment]
顺路 Getting start 中的联系方式换成现在维护的人吧。那两个邮箱都失效了

**Comment by amio** [comment]
有点年久失修了……等确定下后续维护的人和流程，这些都陆陆续续搞起来~

**Comment by blankhua** [comment]
好久不更新了。期待继续维护。

**Comment by leanplay** [comment]
@amio 请问大概多久会在 Github 上看见更新呢？有用 Puerh 做过一个项目 :+1: 。好期待！

**Comment by amio** [comment]
本月内就会有更新 :)

**Comment by leanplay** [comment]
太棒啦！ :100:
