### ISSUE TITLE
仓库建议

### ISSUE THREAD

**Issue by leanplay** [baixing/puerh#25]
1. 添加 min 版本，这样就可以直接引用第三方 cdn 上的资源，比如百度静态资源公共库、Staticfile 等，现在仓库中只有源代码，没有压缩和合并版本，建议添加；
2. 项目名称改成全部小写，即 Puerh 改为 puerh；
3. 编码规范。

**Comment by amio** [comment]
这其实是三个 Issue 了

第一个会做，
第二个建议的理由是什么？
第三个在[文档](http://baixing.github.io/Puerh/start/)里已经有代码规范的一些说明了，是希望增加些内容吗？

**Comment by leanplay** [comment]
## Issue 2 ##

我的原描述有误，其实是指 Github 网址中的大写 P 改为小写 p，但项目名称仍然为 Puerh，理由：

1. 传统意义的网址代表了文件路径，网址中 puerh 对应于一个文件夹或者目录，然后现在很多前端编码规范都规定文件和目录名只限使用小写字母、数字和连字符，所以这里才建议改为小写的 puerh；
2. 大多数项目名都是 Foo，但是在 Github 的网址都都是小写的 foo；
3. 如果 Puerh 首字母大写，那么 baixing 为何不用 Baixing 以保持统一呢？ :wink: 

## Issues 3 ##

我之前是简单看了下代码，是有乱的感觉，所以才提了这点，这个问题等我晚上回去后，再仔细地看看、想想再反馈哈。

**Comment by amio** [comment]
就个人喜好来说，我也倾向用小写 :D 
目前仓库[用小写地址可以访问](https://github.com/baixing/puerh/)，不过[页面不行](http://baixing.github.io/puerh)。

@hax 你有权限来改下这个大小写吗？

**Comment by leanplay** [comment]
嗯。感谢！

**Comment by sofish** [comment]
不如做点真正有意义的事，而不是改个名字的大小字

**Comment by amio** [comment]
其他的也在做，这个比较快看到~

**Comment by amio** [comment]
@leanplay 前两个已经基本完成，第三项如果有详细内容的话新开 Issue 吧，这个我就关闭了
多谢关注 :D
