### ISSUE TITLE
需要添加一个“小圆形带有问号的icon”

### ISSUE THREAD

**Issue by yeiyongjin** [baixing/puerh#30]
![image](https://cloud.githubusercontent.com/assets/11869776/8177246/5750b248-1435-11e5-9e76-f1f7d8e2d6b1.png)
http://post.58.com/471/252/s5?PGTID=14344366869160.5908822936471552&ClickID=1
可以参考该58页面联系电话下方的icon
鼠标Hover上去会出现一个界面

**Comment by yeiyongjin** [comment]
![image](https://cloud.githubusercontent.com/assets/11869776/8177487/d6c41cde-1437-11e5-97f1-1abcd24f95f6.png)
我大致设计了一下，应该是这个样子

**Comment by hax** [comment]
看了下58的这个例子其实不太好。它的提示里面还有“查看详情”的链接，其实不如直接把“(?)”改为“[了解详情]”。另外在它页面的上方也有其他地方用相同图标但是含义不一致的情况。

**Comment by yeiyongjin** [comment]
![image](https://cloud.githubusercontent.com/assets/11869776/8197777/76eaaaf6-14cf-11e5-925e-44dc2de5fa42.png)
大师兄觉察到位，这是我做了一个大致的效果图，请参考
具体还请大师兄抉择

**Comment by reflectioncat** [comment]
现在我们有一个类似的图标的：[image: 内嵌图片 1]
不知是不是你想要的。。

2015-06-17 9:09 GMT+08:00 扰哥 <notifications@github.com>:

**Comment by yeiyongjin** [comment]
我看不到图片呢

**Comment by reflectioncat** [comment]
额。。
如果你知道代码的话，那个icon的名字是icon-question
是一个圆里一个问号，不像你那个是全涂色的，但表达的意思上大概是同一个。

2015-06-17 9:43 GMT+08:00 扰哥 <notifications@github.com>:

**Comment by hax** [comment]
@yeiyongjin 见 http://baixing.github.io/baicons/icons-reference.html

**Comment by yeiyongjin** [comment]
好，就用它了

2015-06-17 12:16 GMT+08:00 HE Shi-Jun <notifications@github.com>:

> @yeiyongjin <https://github.com/yeiyongjin> 见
> http://baixing.github.io/baicons/icons-reference.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baixing/puerh/issues/30#issuecomment-112647547>.
>



-- 


-- 

叶永津  扰哥
18621147350

市场中心Web平台产品经理
百姓网 baixing.com

**Comment by hax** [comment]
呈现的话现有的元素倒是可以凑齐。可能更主要的问题是在现在的fabu配置上是没有地方能做这样的配置的（给某一项加上help信息）。

**Comment by reflectioncat** [comment]
他如果只加在私信或者视频那俩行，是可以手动的。
因为那两行本身就不是从form里出来的。所以不得不放在最后。。
其他的可能得找羊羊羊他们设个新模板了。

在 2015年6月17日 下午12:34，HE Shi-Jun <notifications@github.com>写道：

**Comment by amio** [comment]
看起来大师兄和 KFC 已经把各方面因素都解释到了
@yeiyongjin 没有其他问题的话我把这个 Issue 关掉了？

**Comment by yeiyongjin** [comment]
好的，多谢啦

在 2015年6月18日 下午2:02，Amio <notifications@github.com>写道：

> 看起来大师兄和 KFC 已经把各方面因素都解释到了
> @yeiyongjin <https://github.com/yeiyongjin> 没有其他问题的话我把这个 Issue 关掉了？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baixing/puerh/issues/30#issuecomment-113046671>.
>



-- 


-- 

叶永津  扰哥
18621147350

市场中心Web平台产品经理
百姓网 baixing.com

**Comment by amio** [comment]
@yeiyongjin 放了个图标 + tooltip 的示例，在[这里](http://baixing.github.io/puerh/js/#tips)可以看看效果（Tooltips 示例的最右侧）

**Comment by yeiyongjin** [comment]
效果棒棒的

2015-06-18 16:19 GMT+08:00 Amio notifications@github.com:

> @yeiyongjin https://github.com/yeiyongjin 放了个图标 + tooltip 的示例，在这里
> http://baixing.github.io/puerh/js/#tips可以看看效果（Tooltips 示例的最右侧）
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baixing/puerh/issues/30#issuecomment-113071509.

## 

## 

叶永津  扰哥
18621147350

市场中心Web平台产品经理
百姓网 baixing.com
